---
dependency:
  name: {{ cookiecutter.dependency_name }}
driver:
  name: {{ cookiecutter.driver_name }}
lint:
  name: {{ cookiecutter.lint_name }}
platforms:
{%- if cookiecutter.driver_name == 'docker' %}
  - name: instance
    image: docker.io/pycontribs/centos:7
    pre_build_image: true
{%- elif cookiecutter.driver_name == 'podman' %}
  - name: instance
    image: docker.io/pycontribs/centos:7
    pre_build_image: true
{%- else %}
  - name: instance
{%- endif %}
provisioner:
  name: {{ cookiecutter.provisioner_name }}
  lint:
    name: {{ cookiecutter.provisioner_lint_name }}
    enabled: false
verifier:
  name: {{ cookiecutter.verifier_name }}
  lint:
    name: {{ cookiecutter.verifier_lint_name }}
